### ISSUE TITLE
Comparisons w tolan et al

### ISSUE THREAD

**Issue by JohnMBrandt** [DarthReca/depth-any-canopy#2]
Great work! I’m an author of the tolan et al paper and am interested in the applications of depth anything and better decoders.

id love to be able to learn from your research to improve our future models, which are also trained on NEON patches. Would you be able to share which of the neon patches you discarded? We used all 5600 of them without regard for their quality.

also, we have smaller versions of the ViT weights if you’re interested

**Comment by DarthReca** [comment]
Thanks also for your insightful resource. I am adding the parquet to the repository. 

Note: the EarthView repository is quite messy, and my annotations are made on the Arrow files created by HuggingFace when converting the dataset locally. I wonder if they solved the issues with the dataset.

I would be happy to follow future development

**Comment by DarthReca** [comment]
The information you are searching for is here in [qalign_scores.parquet](https://github.com/DarthReca/depth-any-canopy/blob/main/data/qalign_scores.parquet)
