### ISSUE TITLE
model

### ISSUE THREAD

**Issue by zaoruis** [DarthReca/depth-any-canopy#6]
Did you directly use depth-anythingv2? Have you made any changes to the model structure? Is there a way to use data enhancement?

**Comment by zaoruis** [comment]
![image](https://github.com/user-attachments/assets/6d7255a5-f697-42d6-9e76-c552f940eb50)
Which one is the model weight after you fine-tune it?

**Comment by DarthReca** [comment]
I recommend using the *transformer* library and refer to their documentation:
- *config.json* answers all the questions about the architecture.
- the weights are stored in [safetensor](https://huggingface.co/docs/safetensors/index) format

**Comment by zaoruis** [comment]
> I recommend using the _transformer_ library and refer to their documentation:
> 
> * _config.json_ answers all the questions about the architecture.
> * the weights are stored in [safetensor](https://huggingface.co/docs/safetensors/index) format

Did you directly fine-tune Depthanythingv2? Is it full parameter fine-tuning? Has the model structure changed? Did you just change the data set?

**Comment by zaoruis** [comment]
> I recommend using the _transformer_ library and refer to their documentation:
> 
> * _config.json_ answers all the questions about the architecture.
> * the weights are stored in [safetensor](https://huggingface.co/docs/safetensors/index) format

 Is it full parameter fine-tuning?
